### ISSUE TITLE
Add Our Programmes and Events Components to homepage

### ISSUE THREAD

**Issue by nicholasohjj** [AdvisorySG/dawn-advisory-theme#127]

**Comment by Hackin7** [comment]
What content should I put under that section?
![image](https://user-images.githubusercontent.com/18213722/173192202-5b5a9a01-ae92-4cc2-83ea-301b3a8c8544.png)
Basic UI following the mockup

**Comment by wei2912** [comment]
Addressed on https://github.com/AdvisorySG/dawn-advisory-theme/commit/e9a24b80d311a78469dde70c5c82308a49f9ce6e!
