### ISSUE TITLE
[GPT-6] Home: Style base content of page

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#139]
The current homepage content looks like this:

![image](https://user-images.githubusercontent.com/2070423/176985391-03fd0bfd-1622-4ce6-a76c-dd9d024b15ff.png)

Need to discuss with Marketing on how we'll approach the design of the homepage.

<sub>[GPT-6](https://linear.app/advisorysg/issue/GPT-6/home-style-base-content-of-page)</sub>

**Comment by Hackin7** [comment]
Linked to this issue which is solved https://github.com/AdvisorySG/dawn-advisory-theme/pull/308
