### ISSUE TITLE
Post: Reading progress bar occasionally has large empty space

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#144]
On some posts, e.g. https://beta.advisory.sg/conversations-with-cheah-wenqi/, the reading progress bar displays in this manner:

![image](https://user-images.githubusercontent.com/2070423/179343949-45f66a10-2b7f-44bc-8207-4369e0cc3b6c.png)

There is a large empty space at the top. Not sure why this happens.

**Comment by Hackin7** [comment]
New example is https://beta.advisory.sg/2022/03/29/reflections-with-marcus-loh/, since the previous one is removed

**Comment by Hackin7** [comment]
I figured out the issue, it has something to do with `tag-media` of ghost. It adds an unnecessary margin

![image](https://user-images.githubusercontent.com/18213722/182578050-10e1697f-f9a8-4d3b-9a0a-6b6fe40b521f.png)

![image](https://user-images.githubusercontent.com/18213722/182578078-62e5d03c-eea5-4cbd-abd2-d4e2a799e0e8.png)

This `tag-media` can be found in `assets/css/blog/tag.css`, and it is used in `tag.hbs`
