### ISSUE TITLE
Index: Display full date in Articles list

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#17]
Currently, the articles list only displays a shorthand date e.g. "Dec 05". The year should be displayed alongside this, in the form of "5 Dec 2021".

![image](https://user-images.githubusercontent.com/2070423/142381141-477efa73-0277-4d8e-8dd3-4f3c76e22e0a.png)

**Comment by VedantPol** [comment]
hey @wei2912, I would like to work on this issue :)

**Comment by wei2912** [comment]
@VedantPol Sure, please go ahead and submit a PR!

**Comment by VedantPol** [comment]
thank you for assigning it to me . I will keep on updating you :).if I couldn't feel free to assign it to your devs.

**Comment by wei2912** [comment]
Superseded by https://github.com/AdvisorySG/dawn-advisory-theme/issues/31 which has a date at the bottom right.
