### ISSUE TITLE
[GPT-11] Home: Redesign banners

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#175]
For reference, this is how the banner looks like on my laptop screen (see bottom of page):

![image](https://user-images.githubusercontent.com/2070423/198838309-a365d278-9fcf-4a48-ab25-ffcae461bd46.png)

After increasing the font size of the banner, the height of the banner should ideally be more "substantial" so that it is not easily missed.

<sub>[GPT-11](https://linear.app/advisorysg/issue/GPT-11/home-font-size-on-banners-is-too-small)</sub>

**Comment by wei2912** [comment]
Also consider increasing height of images.

**Comment by wei2912** [comment]
Restyle banners to be in the form of three columns (on desktop), which is more readable than horizontal banners.

**Comment by Hackin7** [comment]
Generally there are a few issues with our home page so I'll tag it all hereFeatured Articles
4. Align Center Tags
5. Padding for Featured Articles
