### ISSUE TITLE
[GPT-10] Stories: List of tags is displayed as a chunk of text

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#176]
Currently, the list of industry tags is displayed as a big chunk of text:

![image](https://user-images.githubusercontent.com/2070423/198838401-0a8d60bd-73f7-4a07-8957-9e9f14973aed.png)

The assignee should research and propose ways to improve the displaying of tags, perhaps taking inspiration from other themes at https://ghost.org/themes/, before starting on any coding.

<sub>[GPT-10](https://linear.app/advisorysg/issue/GPT-10/stories-list-of-tags-is-displayed-as-a-chunk-of-text)</sub>

**Comment by wei2912** [comment]
One possibility (proposed by @BenitaWZX) might be to design a dropdown of some sort to navigate through the tags, although it'll have to look good enough to not be confused for a form input.

**Comment by Hackin7** [comment]
This issue affects various other pages, such as the tags, so these issues should be solved together


![Image](https://user-images.githubusercontent.com/18213722/230953915-6078e4e6-f672-4b37-9f50-24f146e83241.png)


One potential solution to this could be to make the tags more colourful? An example is shown below


![Image](https://user-images.githubusercontent.com/18213722/230954375-389984d3-0c97-4e61-99e8-f2277a67d352.png)
