### ISSUE TITLE
Footer: Font size is inconsistent with navigation

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#179]
The header navigation font size is considerably smaller than that of the footer. For scale, I've included full screenshots on my laptop:

![image](https://user-images.githubusercontent.com/2070423/198838778-20ba6f07-01c5-4342-b295-ce00ac6f522d.png)

![image](https://user-images.githubusercontent.com/2070423/198838781-98b95ef4-05ca-4fb4-806d-e61c71aa5751.png)

**Comment by ChenSirui-016** [comment]
Font sizes are the same
