### ISSUE TITLE
[GPT-17] Search: Display type of result

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#205]
Currently, it is not clear what kind of results are appearing in our search results. It would be good to add some sort of tag, e.g. "Page" or the type of post ("Conversations", "Reflections", etc.).

![image](https://user-images.githubusercontent.com/2070423/210033982-16b606bc-c3dc-4ef1-ba54-56d37581305a.png)

(This is a preliminary idea, might need further discussion/refinement.)

<sub>[GPT-17](https://linear.app/advisorysg/issue/GPT-17/search-display-type-of-result)</sub>

**Comment by Hackin7** [comment]
This should be handled by someone who knows how to tweak the ElasticSearch Results to be able to customise the search results better
