### ISSUE TITLE
[GPT-23] Events: Replace Elfsight Widget 

### ISSUE THREAD

**Issue by Hackin7** [AdvisorySG/dawn-advisory-theme#237]
The Elfsight Widget we have been using has been quite buggy and may not be suitable for the technical MVP #140 
It should ideally be replaced by another widget/ page

Ideally it should be a Card View (or other better view) of Events Sorted by Date (most recent one first).

We could add posts tagged `#events`, which would then be listed in the events page. Other technologies such as AlpineJS and more may help

<sub>[GPT-23](https://linear.app/advisorysg/issue/GPT-23/events-replace-elfsight-widget)</sub>

**Comment by wei2912** [comment]
Might be useful: https://ghost.org/docs/themes/routing/

**Comment by wei2912** [comment]
Or Loxi, see https://loxi.io

**Comment by Hackin7** [comment]
Experiments with Loxi Widget
![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/9739a453-ab33-4fdc-9585-91955ba502b1)
![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/b92faee3-c16c-4475-9c75-af7dd1dedda6)
![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/39277289-8eab-4879-8bc7-e886dd03fa4f)

**Comment by Hackin7** [comment]
I think the Loxi Widget looks decent enough on the website
![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/063b8c44-c7ca-4561-9fe3-68bfd77557df)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/8310d850-c18b-4340-8fa8-18351799c2f6)

Filtering options look usable

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/af852de6-e844-44d3-b8f6-0e08f157182b)

Date filtering looks usable (at the very least, people can scroll through the months to identify events)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/41825079-6970-4fe4-b262-e01303d22c01)

Some downsides may be the colour scheme of loxi, which is green, and that the widget may seem too wide? (at the very least, when viewing an event, it is a chore to scroll down, but may be solvable with custom CSS)
