### ISSUE TITLE
[GPT-24] Tags: Remove More Tags from tag page

### ISSUE THREAD

**Issue by Hackin7** [AdvisorySG/dawn-advisory-theme#242]
![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/399d244e-f5c9-4991-adb8-0b17a9cc49b9)

These tags are unnecessary, and should be removed

<sub>[GPT-24](https://linear.app/advisorysg/issue/GPT-24/tags-remove-more-tags-from-tag-page)</sub>

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it. Please clarify it once.

**Comment by Hackin7** [comment]
Just make a fork and link a pull request here for us to check!

**Comment by Hackin7** [comment]
Just to clarify that its the listing of the tags that should be removed, not the tags themselves

**Comment by Hackin7** [comment]
Somehow its solved? How?
Related code has already been removed
https://github.com/AdvisorySG/dawn-advisory-theme/blob/readme/tag.hbs
https://github.com/AdvisorySG/dawn-advisory-theme/blob/main/tag.hbs
