### ISSUE TITLE
[GPT-33] Post: Create Table of Contents

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#258]
See [https://jez.io/pandoc-markdown-css-theme/](https://jez.io/pandoc-markdown-css-theme/) for inspiration. Should be responsive in design.

<sub>From [SyncLinear.com](https://synclinear.com) | [GPT-33](https://linear.app/advisorysg/issue/GPT-33/post-create-table-of-contents)</sub>

**Comment by Hackin7** [comment]
https://handlebarsjs.com/
https://ghost.org/docs/themes/

/post.hbs

Page css are in /[assets](https://github.com/AdvisorySG/dawn-advisory-theme/tree/main/assets)/[css](https://github.com/AdvisorySG/dawn-advisory-theme/tree/main/assets/css)/site/

https://github.com/AdvisorySG/dawn-advisory-theme/blob/main/assets/js/main.js

**Comment by Hackin7** [comment]
Will be closing it for now since it is not an important issue + we might be moving towards a dropdown format instead
