### ISSUE TITLE
[GPT-35] Footer: Image cannot be seen

### ISSUE THREAD

**Issue by Hackin7** [AdvisorySG/dawn-advisory-theme#267]
![](https://uploads.linear.app/399df041-a1eb-4d3d-bb80-9564252bf082/52308ec7-8854-4791-b7db-b287cae4e889/1eecb1ec-63b6-4974-9142-ac256cdb0d99?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM5OWRmMDQxLWExZWItNGQzZC1iYjgwLTk1NjQyNTJiZjA4Mi81MjMwOGVjNy04ODU0LTQ3OTEtYjdkYi1iMjg3Y2FlNGU4ODkvMWVlY2IxZWMtNjNiNi00OTc0LTkxNDItYWMyNTZjZGIwZDk5IiwiaWF0IjoxNjkxNTA0ODA3LCJleHAiOjE2OTE1OTEyMDd9.heRYSv_9PzqOSP5oUTKfQMsnb_rG9Lm_A013nG_TVc8)

The footer is supposed to be black

![](https://uploads.linear.app/399df041-a1eb-4d3d-bb80-9564252bf082/f60f6494-9d6d-403c-af56-ae09b634e76e/37f223b5-f2a6-4928-a5e0-e984a7c226f3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM5OWRmMDQxLWExZWItNGQzZC1iYjgwLTk1NjQyNTJiZjA4Mi9mNjBmNjQ5NC05ZDZkLTQwM2MtYWY1Ni1hZTA5YjYzNGU3NmUvMzdmMjIzYjUtZjJhNi00OTI4LWE1ZTAtZTk4NGE3YzIyNmYzIiwiaWF0IjoxNjkxNTA0ODA3LCJleHAiOjE2OTE1OTEyMDd9.sJiO4IGXRdEnKH5MiaBdxZbZ_r4OpR0FgK6XyYQsZ1E)

Right now the advisory logo cannot be seen at the footer.

I think 1 possible solution is to make the footer black such that it can be seen

<sub>From [SyncLinear.com](https://synclinear.com) | [GPT-35](https://linear.app/advisorysg/issue/GPT-35/footer-image-cannot-be-seen)</sub>

**Comment by wei2912** [comment]
It used to be black, not sure why lol
