### ISSUE TITLE
Post: Optimise `h1` font size

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#27]
The font size of `h1` headings on devices (especially for mobile) can be quite large and take up a lot of space:

![image](https://user-images.githubusercontent.com/2070423/144704838-bbe3d015-65e2-4dab-894d-759c3bbd5492.png)

Since our articles use questions as headings, the font size should be decreased slightly to increase readability.

**Comment by EliavYair1** [comment]
hi , are you using any kind of UI framworks?
(tailwind/bootstrap/matirial-UI)

if not i suggest you to either use one of those above (my best suggestion is bootstrap) or implanting the @media breakpoints for the media queries
a link at the subject the might help:
[https://www.freecodecamp.org/news/css-media-queries-breakpoints-media-types-standard-resolutions-and-more/](url) 

let me know if the helped you,
goodluck.
