### ISSUE TITLE
[GPT-43] Excessively Long Tag list on mobile

### ISSUE THREAD

**Issue by Hackin7** [AdvisorySG/dawn-advisory-theme#284]
<img width="308" alt="image" src="https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/abdc4593-78fb-406a-8710-5a3f0dbdeb79">

Not too sure on the best way to handle this if its even a good issue, one way I suggest is to make it such that the tags can collapse and expand

<sub>[GPT-43](https://linear.app/advisorysg/issue/GPT-43/excessively-long-tag-list-on-mobile)</sub>

Can look at this for reference
https://github.com/AdvisorySG/dawn-advisory-theme/pull/213

**Comment by Hackin7** [comment]
Potential Idea: tags of tags? like in a hierarchy?

**Comment by jeffzy15** [comment]
There is currently no feature of nested tags in Ghost: https://forum.ghost.org/t/nested-hierarchical-tags-subtags/382.

Hence, to solve this issue I would like to implement a dropdown feature.

**Comment by Hackin7** [comment]
settled by changing to dropdown
