### ISSUE TITLE
[GPT-61] Maximum width of tag

### ISSUE THREAD

**Issue by Hackin7** [AdvisorySG/dawn-advisory-theme#314]
Set a maximum width of the tag
Maybe we can have a maximum of 2 lengthy tags per line and spread it across 2 lines for cases where we have 3 lengthy tags

![](https://uploads.linear.app/399df041-a1eb-4d3d-bb80-9564252bf082/ce0965d8-50b8-492b-86c4-e068356c88ef/32dd029d-bea3-4453-893e-da8a2b0b663f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM5OWRmMDQxLWExZWItNGQzZC1iYjgwLTk1NjQyNTJiZjA4Mi9jZTA5NjVkOC01MGI4LTQ5MmItODZjNC1lMDY4MzU2Yzg4ZWYvMzJkZDAyOWQtYmVhMy00NDUzLTg5M2UtZGE4YTJiMGI2NjNmIiwiaWF0IjoxNzAwNjYxMzQyLCJleHAiOjE3MDA3NDc3NDJ9.dYnMT4s7mnTw_Zh1EeAtoKVWKProtqRtdHYcQxaicf0)

<sub>From [SyncLinear.com](https://synclinear.com) | [GPT-61](https://linear.app/advisorysg/issue/GPT-61/maximum-width-of-tag)</sub>

**Comment by jeffzy15** [comment]
![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/7eb3aee7-f465-4f51-b7a0-4338687720c1)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/389028e5-4485-441b-8e80-e2ef3b1882b0)

**Comment by Hackin7** [comment]
decided against it
