### ISSUE TITLE
[GPT-62] Experiment with Switching Position of Title and tags

### ISSUE THREAD

**Issue by Hackin7** [AdvisorySG/dawn-advisory-theme#315]
![](https://uploads.linear.app/399df041-a1eb-4d3d-bb80-9564252bf082/a967e7fe-d720-44a8-8127-e044c2554bea/bfcc0b07-d37c-427d-ad0b-d0c33b90d81d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM5OWRmMDQxLWExZWItNGQzZC1iYjgwLTk1NjQyNTJiZjA4Mi9hOTY3ZTdmZS1kNzIwLTQ0YTgtODEyNy1lMDQ0YzI1NTRiZWEvYmZjYzBiMDctZDM3Yy00MjdkLWFkMGItZDBjMzNiOTBkODFkIiwiaWF0IjoxNzAwNjYxNDM1LCJleHAiOjE3MDA3NDc4MzV9.RzN_CZ5Bug8La1kpqJ5SYETWMl1h20sWWwHUoRPKvo4)

Switch the position of the title and tags and paste an image in a related PR so that we can decide if this is the direction to head in

Feel free to experiment with various combinations and paste their screenshots. Paste screenshots with various posts/ screensizes too

Sample ordering

```
[Title]
[info]
[Tags]
```

or

```
[title]
[tags]
[info]
```

<sub>From [SyncLinear.com](https://synclinear.com) | [GPT-62](https://linear.app/advisorysg/issue/GPT-62/experiment-with-switching-position-of-title-and-tags)</sub>

**Comment by jeffzy15** [comment]
<h1>Title, Info, Tags:</h1>
![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/2272b6c8-6743-4dd5-8a80-80f052f76511)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/830b2745-9140-4cad-a59a-bbaf34b303fd)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/7e2afef6-69c3-4e2f-ba99-700ea40232f6)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/5ea3d99b-14c0-4d9f-8dd4-36ef3c78a9d3)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/b00724e1-3ee6-409a-9023-79b590f6308c)


<h1> Title, Tags, Info: </h1>

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/4e3991b1-8fb5-48e5-91e5-d6bf91f99e60)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/a9d06293-4877-4825-b88a-800dad3089f3)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/50887c83-4fca-476d-86e3-c8becc106fa6)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/5aa66d6c-f786-42b8-a1b1-8e1f860e8af6)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/333f919e-1d8e-4075-a96d-135fbc49455a)

**Comment by jeffzy15** [comment]
As mentioned in https://github.com/AdvisorySG/dawn-advisory-theme/issues/306#issuecomment-1822873509: 

The 2nd layout would look nicer with single tags left-justified

**Comment by jeffzy15** [comment]
Resending for mobile view with all changes collated (from various PRs)

<h1> Original </h1>

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/715fe7ac-ff85-4477-9b4d-8d8aafc01034)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/baffd162-f2f1-4f09-8374-ae16711151c1)

<h1> Title, Info, Tags </h1>

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/fd77d371-d231-4fdb-9efe-5f12b9ceb4a3)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/64253817-0a4e-4a85-9a8e-c4bd42642674)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/119c6b18-5da6-4e58-93de-12b30cf615e1)

<h1> Title, Tags, Info </h1>

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/ac34e55f-23d0-440d-963a-9db3b1b6b0b9)

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/7f18bbc2-59ca-470c-bc01-22a64be37ec2)

**Comment by jeffzy15** [comment]
No PR has been opened yet since the design has not been confirmed yet

**Comment by Aelderic** [comment]
Tags to be either above the title or below the title. Might want to explore changing the bubble text look away

**Comment by Hackin7** [comment]
For now there's not much negative feedback on PCSC from this, so I'll close this issue, and reopen/ recreate it as needed
