### ISSUE TITLE
[GPT-63] Search: Page excerpts are sometimes not displayed

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#318]
![image](https://uploads.linear.app/399df041-a1eb-4d3d-bb80-9564252bf082/e1620614-d7d1-4516-b8f6-aa29d27709e2/8aed8b72-ea8f-4cf5-a009-8fe4e84fe96a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM5OWRmMDQxLWExZWItNGQzZC1iYjgwLTk1NjQyNTJiZjA4Mi9lMTYyMDYxNC1kN2QxLTQ1MTYtYjhmNi1hYTI5ZDI3NzA5ZTIvOGFlZDhiNzItZWE4Zi00Y2Y1LWEwMDktOGZlNGU4NGZlOTZhIiwiaWF0IjoxNzAxMjYwMTMwLCJleHAiOjE3MDEzNDY1MzB9.UWWTq0V745lq9L3pfMBiDSoIQzrm54p4zy0ViOV24VA)

<sub>From [SyncLinear.com](https://synclinear.com) | [GPT-63](https://linear.app/advisorysg/issue/GPT-63/page-excerpts-are-sometimes-not-displayed)</sub>

**Comment by jeffzy15** [comment]
<img width="1030" alt="image" src="https://github.com/AdvisorySG/dawn-advisory-theme/assets/73103636/05a92c85-0b41-4773-bdb6-dd22d4517a8f">

It seems that there is an issue with displaying the body content of pages. All pages do not display any info when searched

**Comment by wei2912** [comment]
Closing since we are removing search feature for launch.
