### ISSUE TITLE
[GPT-81] Home: Add 1st section to be about what the organisation does

### ISSUE THREAD

**Issue by Hackin7** [AdvisorySG/dawn-advisory-theme#335]
<img width="682" alt="image" src="https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/f6bbb97a-4b83-4efe-b7b7-51a4f0313f53">

Example idea

<sub>[GPT-81](https://linear.app/advisorysg/issue/GPT-81/home-add-1st-section-to-be-about-what-the-organisation-does)</sub>

**Comment by wei2912** [comment]
To create a design prototype (no need to write anything sensible).
