### ISSUE TITLE
Stories: Implement industry filtering

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#351]
Currently, tags are displayed as a large row of mixed-width pills:

![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/2070423/133a9c2e-82d3-438a-be7d-c752a79540df)

This isn't really easy to navigate and should be changed into a dropdown filter which allows for multiple industries to be selected.

**Comment by Hackin7** [comment]
![image](https://github.com/AdvisorySG/dawn-advisory-theme/assets/18213722/d1c72084-640a-4e37-9719-83df3b4c20ca)

the tags would ideally be something more like this for website launch, to be discussed if we can keep with this
