### ISSUE TITLE
The Team: Headings Standardisation

### ISSUE THREAD

**Issue by Hackin7** [AdvisorySG/dawn-advisory-theme#355]
The Team Page
Headings - "The Team" shld be the largest, subsequent headings like "BOARD OF ADVISORS" should follow consistent style (h2, not all caps)

**Comment by Famoushealer** [comment]
Done! Brother, i sent to terence the codes already. Feel free to view the attached as well!
[Uploading advisory team.txt…]()

**Comment by wei2912** [comment]
Addressed in https://github.com/AdvisorySG/dawn-advisory-theme/commit/d7d91e75229d747c196a2042c5b927223642a211, with help from @Famoushealer.
