### ISSUE TITLE
Stories: Reimplement Stories Search Feature

### ISSUE THREAD

**Issue by Hackin7** [AdvisorySG/dawn-advisory-theme#397]
1. ElasticSearch might be too complex for our needs, we don't need a site wide search feature

Just want to search through the post and filter by industry

see https://github.com/jameslittle230/stork/discussions/360 for list of suggested search libraries

**Comment by wei2912** [comment]
https://pagefind.app/ seems the most promising so far, but will leave it to assigned dev to do further research

**Comment by wei2912** [comment]
...also apparently there's a native Ghost search that's been implemented for a long while.

https://ghost.org/changelog/search/
https://forum.ghost.org/t/how-can-i-make-search-pages-also/32351/14
