### ISSUE TITLE
Search: Replace search engine

### ISSUE THREAD

**Issue by partysnax** [AdvisorySG/dawn-advisory-theme#51]
The current search engine used (Elasticlunr) does not support queries with partial/truncated words, eg. searching "conversa" does not bring up any of the articles with "Conversations" in the title. This appears to be the design of the search engine itself that cannot be rectified using configurations. Hence a different search engine can be used.

**Comment by fabform** [comment]
Handy alternative list of [alternative search engines](https://fabform.io/a/alternative-search-engines)

**Comment by wei2912** [comment]
Currently exploring using Algolia Docsearch for a more straightforward setup, as the free plan of Algolia should be sufficient for our usecases (10000 searches/month, where a search is incurred on every keypress).

However, as v3 requires the use of Algolia Crawler which costs quite a lot to use, I'm looking into the use of Docsearch v2 which uses a command-line crawler that can be runned on our own server. See the following for more details: https://panaetius.io/post/2021/10/add-search-to-a-hugo-website-using-algolia-docsearch/

**Comment by wei2912** [comment]
See following links:
1. https://github.com/AdvisorySG/dockerfiles (docker compose setup)
2. https://docsearch.algolia.com/docs/legacy/run-your-own (note that Algolia DocSearch v2 should be used)

For docker compose setup, need to create `algolia.env` with the following variables (to be obtained from Algolia):
```
APPLICATION_ID=...
API_KEY=...
```

**Comment by wei2912** [comment]
Crawler side is unfortunately quite frustrating to set up on the server. I tried setting up the Elastic Search crawler which works much smoother, but there's no simple UI for search functionality out there afaik. There's Elastic Site Search but it's super expensive.
