### ISSUE TITLE
Post Cards: Slight discrepancy between tagless and tagged articles

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#67]
![image](https://user-images.githubusercontent.com/2070423/151644548-0f0ed89d-c05c-497f-a4b2-85e33d4290d6.png)

As seen above, the title of the tagless article is slightly above that of the tagged article.

**Comment by SJellen** [comment]
Wouldn't it be better to not show [No tag] ? 
The issue would still remain, but it would not draw attention to a null item. just a thought.

**Comment by wei2912** [comment]
@SJellen We were intending to draw attention to the lack of tags, as all of our articles are expected to have industry tags. Thanks for the suggestion anyways!

**Comment by wei2912** [comment]
Resolved in https://github.com/AdvisorySG/dawn-advisory-theme/commit/00b86190fed2b20f2554fdd869bb1fb45f6a851d.
