### ISSUE TITLE
Header: Add top margin to navbar

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#68]
![image](https://user-images.githubusercontent.com/2070423/151651925-9d6da34e-b644-4481-b41f-0445c449136f.png)

Currently, the Advisory logo at the top left of the header is too close to the top of the page. Some breathing space should be added.

**Comment by MThabsheer7** [comment]
Hey @wei2912 , I can do this.

**Comment by wei2912** [comment]
> Hey @wei2912 , I can do this.

Sure, please leave a PR for review! We may reassign the issue to someone else if there's no PR submitted in the next 2 weeks. Thanks in advance!

**Comment by MThabsheer7** [comment]
Okay I'm on it.

**Comment by wei2912** [comment]
This issue will be assigned to @Uselesstrash06.
