### ISSUE TITLE
Footer: Update Advisory's social media icons

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/dawn-advisory-theme#7]
Currently, the website only displays Facebook and RSS for Advisory's social media links in the footer:

![image](https://user-images.githubusercontent.com/2070423/142376731-9218f1e5-66ba-4108-abfa-06a752e57d39.png)

These should be replaced with the relevant social media icons (check with Marketing to get the most recent links).

Please see the following related issues/PRs:
1. https://github.com/AdvisorySG/ghost-advisory-theme/issues/292
2. https://github.com/AdvisorySG/ghost-advisory-theme/pull/314

**Comment by Eykf1997** [comment]
Hello Wei En, I wouldn't mind working on this issue!

**Comment by oneamanish** [comment]
see my pull req.

**Comment by wei2912** [comment]
Fixed in https://github.com/AdvisorySG/dawn-advisory-theme/commit/c9db9808056a9a7f1dce2545285531cfaf4cee5f.
