### ISSUE TITLE
[GPT-7] possible audio publishing using beyondwords

### ISSUE THREAD

**Issue by nicholasohjj** [AdvisorySG/dawn-advisory-theme#97]
https://beyondwords.io/
**Sample output**

https://beta.advisory.sg/insights-on-e-commerce/
https://beta.advisory.sg/conversations-with-ee-ling-lim/

<sub>[GPT-7](https://linear.app/advisorysg/issue/GPT-7/possible-audio-publishing-using-beyondwords)</sub>

**Comment by wei2912** [comment]
Closing for now - might revisit in future, though unlikely we have the bandwidth for this.
